### ISSUE TITLE
Open ports should only refer to ports the bootstrap daemon is listening on

### ISSUE THREAD

**Issue by LittleVulpix** [Tox/ToxStatus#16]
It is possible that you have port 443 opened because you're hosting a https website, or that you actually really use remote desktop protocol (port 3389) for remote desktop.

If this is the case, ToxStatus will still say that your bootstrap node is listening on those ports - which is not the case. It could lead to people trying to bootstrap off of a node at IP XXXX port 443 where the daemon actually isn't listening.

I don't exactly know how the bootstrap nodes are queried for information, but since you can obtain the MOTD, isn't there a way you can also query the node for its list of enabled ports and probe only those?

**Comment by alexbakker** [comment]
Thanks for reminding me about this issue.

There is no way to query a bootstrap node for its open TCP ports. Currently ToxStatus tries to get a TCP relay handshake response on the default ports (443, 3389 and 33445). This works, but there's a logic bug in the code that makes it report every port that listens on TCP, not just the ones that respond to TCP relay handshake requests, which is why you see the HTTPS ports pop up as well.

I have a bunch of other changes mixed with a fix for this issue in a branch locally. I'll try to get it pushed soon.

**Comment by LittleVulpix** [comment]
Sounds great! Thanks!

**Comment by alexbakker** [comment]
I'm currently test-driving the 'rework' branch at https://nodes.tox.chat/beta. This issue should be fixed there.
