### ISSUE TITLE
Cannot connect to node with 443 UDP port

### ISSUE THREAD

**Issue by dvor** [Tox/ToxStatus#19]
For nodes that use 443 UDP port following message is shown on website:

> Unable connect to this node through UDP. A TCP relay seems to be up and running, however.

**Comment by alexbakker** [comment]
I'd be surprised if this actually has anything to do with the port number. I'll investigate.

**Comment by alexbakker** [comment]
So I looked into this. It turns out Digital Ocean (the platform nodes.tox.chat is hosted on) blocks outgoing UDP packets to port 443. A quick chat with their support team confirmed this.

I was told that it's possible to have this port unblocked, but it requires an "extensive review" because "it is a known vector for exploitation and DDoS attacks". If this process turns out to be a hassle or if the request is declined, I'll have to switch to a different provider. Scaleway seems like a good option, but it requires a credit card, so I have to get myself one of those first. (I might end up switching to Scaleway anyway as they seem cheaper)

**Comment by alexbakker** [comment]
A formal request was submitted by a Digital Ocean support team member 14 days ago. I asked for a status update 2 days ago. I was told that they "haven't had any movement on this" as "this isn't a port we've opened before" and they can't give me "an estimated time of resolution right now".

This is taking too long. I'm going to switch to Scaleway. It will take _at least_ another 2 weeks before this issue gets fixed, as I have to request a credit card first. Sigh.

**Comment by alexbakker** [comment]
That was faster than I anticipated. I just spun up an instance on Scaleway and the issue doesn't appear there :)

I'm going to request record changes for nodes.tox.chat and close this issue once the migration is complete.

**Comment by alexbakker** [comment]
Fixed!

**Comment by dvor** [comment]
Nice, thanks!
